const c=document.querySelector('#game'),g=c.getContext('2d');g.imageSmoothingEnabled=false;const W=800,H=600,C=25,OX=25,OY=75,COLS=30,ROWS=19;let score=0,lives=3,state='play',last=performance.now(),power=0,mouth=0;
const grid=Array.from({length:ROWS},()=>Array(COLS).fill(0));
function carve(x,y){if(x>=0&&x<COLS&&y>=0&&y<ROWS)grid[y][x]=1}function h(y,a,b){for(let x=a;x<=b;x++)carve(x,y)}function v(x,a,b){for(let y=a;y<=b;y++)carve(x,y)}
// Corredores principais desenhando A C R E no centro, interligados por moldura arcade.
h(0,1,28);h(18,1,28);v(1,0,18);v(28,0,18);h(4,1,28);h(14,1,28);h(9,1,28);[5,11,18,24].forEach(x=>v(x,0,18));
// A
h(6,3,8);h(11,3,8);v(3,6,13);v(8,6,13);carve(4,5);carve(7,5);h(5,4,7);
// C
h(5,10,15);h(13,10,15);v(10,5,13);h(9,10,13);
// R
v(17,5,13);h(5,17,21);h(9,17,21);v(21,5,9);for(let i=0;i<5;i++)carve(18+i,9+i);
// E
v(23,5,13);h(5,23,27);h(9,23,27);h(13,23,27);
// ligações adicionais
[2,7,12,16].forEach(y=>h(y,1,28));
const dots=new Set();for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++)if(grid[y][x])dots.add(x+','+y);const powers=new Set(['1,0','28,0','1,18','28,18']);
const pac={x:1,y:18,dir:{x:1,y:0},next:{x:1,y:0},px:1,py:18,t:0};const ghostStarts=[[14,9],[15,9],[14,10],[15,10]],cols=['#ef3f3f','#f5a6d7','#52d9e8','#f2a13d'];const ghosts=ghostStarts.map((p,i)=>({x:p[0],y:p[1],px:p[0],py:p[1],t:0,dir:{x:i%2?1:-1,y:0},col:cols[i],home:[...p]}));
function open(x,y){return x>=0&&x<COLS&&y>=0&&y<ROWS&&grid[y][x]}function key(x,y){return x+','+y}function resetPositions(){Object.assign(pac,{x:1,y:18,px:1,py:18,t:0,dir:{x:1,y:0},next:{x:1,y:0}});ghosts.forEach((q,i)=>Object.assign(q,{x:q.home[0],y:q.home[1],px:q.home[0],py:q.home[1],t:0,dir:{x:i%2?1:-1,y:0}}))}function lose(){lives--;power=0;if(lives<=0)state='over';else resetPositions()}
addEventListener('keydown',e=>{const m={ArrowLeft:{x:-1,y:0},ArrowRight:{x:1,y:0},ArrowUp:{x:0,y:-1},ArrowDown:{x:0,y:1}};if(m[e.code]){e.preventDefault();pac.next=m[e.code]}if(e.code==='Escape')location.href='index.html';if(e.code==='Enter'&&state==='over')location.reload()});
function chooseGhost(q){const opts=[{x:1,y:0},{x:-1,y:0},{x:0,y:1},{x:0,y:-1}].filter(d=>open(q.x+d.x,q.y+d.y)&&!(d.x===-q.dir.x&&d.y===-q.dir.y));if(!opts.length)return{x:-q.dir.x,y:-q.dir.y};if(power>0)return opts[Math.floor(Math.random()*opts.length)];opts.sort((a,b)=>{const da=Math.abs(q.x+a.x-pac.x)+Math.abs(q.y+a.y-pac.y),db=Math.abs(q.x+b.x-pac.x)+Math.abs(q.y+b.y-pac.y);return da-db});return Math.random()<.72?opts[0]:opts[Math.floor(Math.random()*opts.length)]}
function stepEntity(o,speed,isPac=false){o.t+=speed;if(o.t<1)return;o.t-=1;o.px=o.x;o.py=o.y;if(isPac&&open(o.x+pac.next.x,o.y+pac.next.y))o.dir=pac.next;if(!open(o.x+o.dir.x,o.y+o.dir.y)){if(isPac){o.t=0;return}else o.dir=chooseGhost(o)}o.x+=o.dir.x;o.y+=o.dir.y;if(!isPac)o.dir=chooseGhost(o)}
function update(dt){if(state!=='play')return;mouth+=dt*12;if(power>0)power=Math.max(0,power-dt);stepEntity(pac,dt*7.3,true);const k=key(pac.x,pac.y);if(dots.has(k)){dots.delete(k);score+=10;if(powers.has(k)){powers.delete(k);power=7;score+=40}}ghosts.forEach(q=>stepEntity(q,dt*(power>0?4.3:5.5)));for(const q of ghosts){if(Math.abs(q.x-pac.x)+Math.abs(q.y-pac.y)<=0&&q.t<.7&&pac.t<.7){if(power>0){score+=200;Object.assign(q,{x:q.home[0],y:q.home[1],px:q.home[0],py:q.home[1],t:0})}else{lose();return}}}if(dots.size===0){state='win';setTimeout(()=>location.href='index.html',2300)}}
function pos(o){return{x:OX+(o.px+(o.x-o.px)*o.t)*C+C/2,y:OY+(o.py+(o.y-o.py)*o.t)*C+C/2}}function circle(x,y,r,col){g.fillStyle=col;g.beginPath();g.arc(x,y,r,0,Math.PI*2);g.fill()}
function drawGhost(q){const p=pos(q),blue=power>0;g.fillStyle=blue?'#235bd8':q.col;g.beginPath();g.arc(p.x,p.y-2,10,Math.PI,0);g.lineTo(p.x+10,p.y+10);g.lineTo(p.x+5,p.y+6);g.lineTo(p.x,p.y+10);g.lineTo(p.x-5,p.y+6);g.lineTo(p.x-10,p.y+10);g.closePath();g.fill();circle(p.x-4,p.y-3,3,'#fff');circle(p.x+4,p.y-3,3,'#fff');circle(p.x-4+(blue?0:q.dir.x*1.5),p.y-3+q.dir.y*1.5,1.5,blue?'#fff':'#1840a0');circle(p.x+4+(blue?0:q.dir.x*1.5),p.y-3+q.dir.y*1.5,1.5,blue?'#fff':'#1840a0')}
function drawPac(){const p=pos(pac),a=Math.abs(Math.sin(mouth))*.55,ang=Math.atan2(pac.dir.y,pac.dir.x);g.fillStyle='#ffd928';g.beginPath();g.moveTo(p.x,p.y);g.arc(p.x,p.y,11,ang+a,ang+Math.PI*2-a);g.closePath();g.fill()}
function draw(){g.fillStyle='#000';g.fillRect(0,0,W,H);g.strokeStyle='#174cff';g.lineWidth=3;for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++)if(!grid[y][x]){const X=OX+x*C,Y=OY+y*C;g.strokeRect(X+2,Y+2,C-4,C-4)}g.fillStyle='#f6d9a4';for(const s of dots){const [x,y]=s.split(',').map(Number),X=OX+x*C+C/2,Y=OY+y*C+C/2;circle(X,Y,powers.has(s)?6:2.2,'#f6d9a4')}drawPac();ghosts.forEach(drawGhost);g.fillStyle='#fff';g.font='bold 20px monospace';g.fillText('1UP',35,28);g.fillText(String(score).padStart(6,'0'),35,51);g.fillText('PAC-MAN ACRE',310,38);g.fillText('VIDAS '+lives,650,38);if(power>0){g.fillStyle='#59a8ff';g.fillText('POWER '+power.toFixed(1),330,580)}if(state!=='play'){g.fillStyle='#000';g.fillRect(235,250,330,95);g.fillStyle='#fff';g.textAlign='center';g.font='bold 26px monospace';g.fillText(state==='win'?'FASE COMPLETA!':'GAME OVER',400,290);g.font='16px monospace';g.fillText(state==='win'?'VOLTANDO À SALA...':'ENTER PARA RECOMEÇAR',400,325);g.textAlign='left'}}function loop(n){const dt=Math.min(.033,(n-last)/1000);last=n;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);