const c=document.querySelector('#game'),x=c.getContext('2d');
const W=c.width,H=c.height,keys={};let bullets=[],enemies=[],fuel=100,score=0,level=1,scroll=0,spawn=0,bridge=false,over=false;
const plane={x:W/2,y:H-100,w:26,h:34,speed:260};
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space'){e.preventDefault();shoot()}if(e.code==='Escape')location.href='index.html'});addEventListener('keyup',e=>keys[e.code]=false);
function shoot(){if(over)return;bullets.push({x:plane.x,y:plane.y-22});}
function enemy(){const types=['boat','heli','jet','fuel'];const type=types[Math.floor(Math.random()*types.length)];enemies.push({type,x:150+Math.random()*(W-300),y:-40,v:90+Math.random()*80,dir:Math.random()<.5?-1:1,w:type==='fuel'?44:32,h:24});}
function hit(a,b){return Math.abs(a.x-b.x)<(a.w+b.w)/2&&Math.abs(a.y-b.y)<(a.h+b.h)/2}
function reset(){plane.x=W/2;fuel=100;bullets=[];enemies=[];over=false;bridge=false;scroll=0;}
function update(dt){if(over){if(keys.Enter){score=0;level=1;reset()}return}scroll+=150*dt;fuel-=2.1*dt;if(fuel<=0)over=true;if(keys.ArrowLeft||keys.KeyA)plane.x-=plane.speed*dt;if(keys.ArrowRight||keys.KeyD)plane.x+=plane.speed*dt;plane.x=Math.max(120,Math.min(W-120,plane.x));bullets.forEach(b=>b.y-=440*dt);bullets=bullets.filter(b=>b.y>-20);spawn-=dt;if(spawn<=0&&!bridge){enemy();spawn=Math.max(.35,1.15-level*.12)}enemies.forEach(e=>{e.y+=e.v*dt;if(e.type==='heli'||e.type==='jet'){e.x+=e.dir*75*dt;if(e.x<120||e.x>W-120)e.dir*=-1}if(e.type==='fuel'&&Math.abs(e.x-plane.x)<35&&Math.abs(e.y-plane.y)<45)fuel=Math.min(100,fuel+28*dt)});for(const b of bullets)for(const e of enemies)if(!e.dead&&hit({x:b.x,y:b.y,w:5,h:12},e)){e.dead=true;b.dead=true;if(e.type!=='fuel')score+=e.type==='jet'?150:100}bullets=bullets.filter(b=>!b.dead);enemies=enemies.filter(e=>!e.dead&&e.y<H+50);for(const e of enemies)if(e.type!=='fuel'&&hit(plane,e))over=true;if(scroll>4200*level&&!bridge){bridge=true;enemies.push({type:'bridge',x:W/2,y:-30,v:110,w:390,h:30})}const br=enemies.find(e=>e.type==='bridge');if(br){for(const b of bullets)if(!br.dead&&hit({x:b.x,y:b.y,w:5,h:12},br)){br.dead=true;b.dead=true;score+=500;level++;bridge=false;scroll=0;if(level>2){over=true}else enemies=enemies.filter(e=>e!==br)}}}
function pixelText(s,a,b,size=18){x.font=`bold ${size}px monospace`;x.fillStyle='#fff';x.fillText(s,a,b)}
function drawPlane(px,py){x.fillStyle='#f2e85c';x.fillRect(px-5,py-18,10,36);x.fillRect(px-18,py,36,8);x.fillStyle='#e34b43';x.fillRect(px-3,py-13,6,8)}
function drawEnemy(e){if(e.type==='fuel'){x.fillStyle='#eee';x.fillRect(e.x-22,e.y-10,44,20);x.fillStyle='#e24b3f';x.fillRect(e.x-15,e.y-3,30,6);x.fillStyle='#222';x.font='10px monospace';x.fillText('FUEL',e.x-13,e.y+4);return}if(e.type==='bridge'){x.fillStyle='#9b6b35';x.fillRect(90,e.y-12,W-180,24);x.fillStyle='#333';for(let i=100;i<W-100;i+=35)x.fillRect(i,e.y-16,8,32);return}x.fillStyle=e.type==='heli'?'#74d66a':e.type==='jet'?'#ddd':'#d58b36';if(e.type==='boat'){x.fillRect(e.x-16,e.y-5,32,12);x.fillRect(e.x-6,e.y-12,12,8)}else if(e.type==='heli'){x.fillRect(e.x-12,e.y-7,24,14);x.fillRect(e.x-22,e.y-13,44,3);x.fillRect(e.x+10,e.y-3,14,3)}else{x.beginPath();x.moveTo(e.x,e.y-14);x.lineTo(e.x-18,e.y+10);x.lineTo(e.x,e.y+5);x.lineTo(e.x+18,e.y+10);x.fill()}}
function draw(){x.fillStyle='#247d38';x.fillRect(0,0,W,H);const wave=Math.sin(scroll*.003)*35;x.fillStyle='#1760a8';x.beginPath();x.moveTo(100+wave,0);for(let y=0;y<=H;y+=60)x.lineTo(90+Math.sin((y+scroll)*.004)*45,y);x.lineTo(W-90+Math.sin((H+scroll)*.004)*45,H);for(let y=H;y>=0;y-=60)x.lineTo(W-90+Math.sin((y+scroll)*.004)*45,y);x.closePath();x.fill();x.fillStyle='#72b94c';for(let y=0;y<H;y+=80){x.fillRect(40+(y%160),((y+scroll)%H),20,8);x.fillRect(W-70-(y%120),((y+scroll*1.2)%H),18,7)}enemies.forEach(drawEnemy);x.fillStyle='#fff';bullets.forEach(b=>x.fillRect(b.x-2,b.y-8,4,12));drawPlane(plane.x,plane.y);x.fillStyle='#000b';x.fillRect(0,0,W,45);pixelText(`SCORE ${String(score).padStart(6,'0')}`,16,29);pixelText(`FASE ${Math.min(level,2)}`,260,29);pixelText('FUEL',450,29);x.strokeStyle='#fff';x.strokeRect(500,15,120,14);x.fillStyle=fuel<25?'#f44':'#f0d64b';x.fillRect(502,17,116*Math.max(0,fuel)/100,10);if(over){x.fillStyle='#000c';x.fillRect(90,270,W-180,150);x.textAlign='center';pixelText(level>2?'MISSÃO COMPLETA!':'GAME OVER',W/2,325,30);pixelText(level>2?'DUAS FASES CONCLUÍDAS':'ENTER PARA RECOMEÇAR',W/2,365,16);x.textAlign='left'}}
let last=performance.now();function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);